apiVersion: v1
kind: Secret
metadata:
  name: azdevops
  namespace: azdevops-agents
type: Opaque
stringData:
  AZP_POOL: poolname
  AZP_TOKEN: myuniquetoken
  AZP_URL: https://dev.azure.com/myorganisation